apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: go-rest                  # Name of the Kubernetes resource
spec:
  replicas: 3                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: go-rest               # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: go-rest 
    spec:                        # Spec for the container which will run in the Pod
      containers:
      - name: go-rest
        image: vishweshc/go-rest:1.0.0
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
          - containerPort: 8080  # Should match the port number that the Go application listens on
        livenessProbe:           # To check the health of the Pod
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 5
        readinessProbe:          # To check if the Pod is ready to serve traffic or not
          httpGet:
            path: /readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 1 
---
# service
apiVersion: v1
kind: Service                    # Type of kubernetes resource
metadata:
  name: go-rest-service   # Name of the resource
spec:
  type: LoadBalancer                 # A port is opened on each node in your cluster via Kube proxy.
  ports:                         # Take incoming HTTP requests on port 9090 and forward them to the targetPort of 8080
  - name: http
    port: 9090
    targetPort: 8080
  selector:
    app: go-rest         # Map any pod with label `app=go-hello-world` to this service